### ISSUE TITLE
Корректный парсинг строки

### ISSUE THREAD

**Issue by Pitovsky** [max-dankow/My_Bash#3]
1. Деление по пробелам (уже есть, но)
2. Параметр в кавычках не должен учитывать пробелы и должен убрать сами кавычки (типо echo "first second" должна быть поделена на (echo) и (first second))
3. Обработка операторов - символы типа '>' и '>>', '&&' и прочие должны прерывать парсинг и вызывать соответств. функции (перенаправление потоков, распараллеливание процессов и т.п.)

**Comment by max-dankow** [comment]
Еще обработка последавательного запуска comand1; comand2; ...
